# DATA LOADING AND DATA STORAGE :-

DATA  SOURCE ->
DATA LOAD -> PANDAS
DATAFRAME -> DATA
INSPECTION -> DATA
STORAGE -> CSV,JSON,EXCEL etc

In [1]:
import pandas as pd

In [2]:
import os
#SEE THE DIRECTORY :-
print(os.getcwd())

/content

In [3]:
# TO SEE THE LIST OF DIRECTORY [FILES AND FOLDERS]:-
print(os.listdir())

['.config', 'sample_data']

In [ ]:
#csv file using read and write
import pandas as pd

# 1. Sample Data Dataframe banao
data = {
    'Name': ['Amit', 'Priya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mathura', 'Agra']
}
df = pd.DataFrame(data)

# 2. DataFrame ko CSV file me save karo (Write)
file_name = "name.csv"
df.to_csv(file_name, index=False)
print(f"File '{file_name}' successfully create ho gayi!")

# 3. Created CSV file ko padho (Read)
df_read = pd.read_csv(file_name)
print("\nFile se padha gaya Data:")
print(df_read)

File 'name.csv' successfully create ho gayi!

File se padha gaya Data:
    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

EXCEL FILE CONVERT :-

In [ ]:
# 1. Sample DataFrame

data = {
    'Name': ['Amit', 'Priya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mathura', 'Agra']
}
df = pd.DataFrame(data)
# 2. DataFrame ko Excel file (.xlsx) me write karo

excel_file = "name.xlsx"
df.to_excel(excel_file, index=False, sheet_name='Sheet1')

print(f"File '{excel_file}' successfully create ho gayi!")

# 3. Created Excel file ko read karke verify karo
df_excel = pd.read_excel(excel_file)
print("\nExcel File se padha gaya Data:")
print(df_excel)

File 'name.xlsx' successfully create ho gayi!

Excel File se padha gaya Data:
    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

JSON FILE CONVERT :-

In [ ]:
# 1. Sample DataFrame
data = {
    'Name': ['Amit', 'Priya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mathura', 'Agra']
}
df = pd.DataFrame(data)

# 2. DataFrame ko JSON file me write (save) karo
json_file = "name.json"
df.to_json(json_file, orient='records', indent=4)

print(f"File '{json_file}' successfully create ho gayi!")

# 3. Created JSON file ko read karke verify karo
df_json = pd.read_json(json_file)
print("\nJSON File se padha gaya Data:")
print(df_json)

File 'name.json' successfully create ho gayi!

JSON File se padha gaya Data:
    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

TAB FILE CONVERT :-

In [ ]:
# 1. Sample DataFrame
data = {
    'Name': ['Amit', 'Priya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mathura', 'Agra']
}
df = pd.DataFrame(data)

# 2. DataFrame ko Tab-Separated file (.tsv ya .txt) me save karo
tsv_file = "name.tsv"
df.to_csv(tsv_file, sep='\t', index=False)

print(f"File '{tsv_file}' successfully create ho gayi!")

# 3. Created TSV file ko read karke verify karo
df_tsv = pd.read_csv(tsv_file, sep='\t')
print("\nTSV File se padha gaya Data:")
print(df_tsv)

File 'name.tsv' successfully create ho gayi!

TSV File se padha gaya Data:
    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

FWF FILE CONVERT :-

In [ ]:
# 1. Sample DataFrame
data = {
    'Name': ['Amit', 'Priya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mathura', 'Agra']
}
df = pd.DataFrame(data)

# 2. DataFrame ko FWF file (.txt ya .fwf) me save karo
fwf_file = "name.fwf"
with open(fwf_file, "w") as f:
    f.write(df.to_string(index=False))

print(f"File '{fwf_file}' successfully create ho gayi!")

# 3. Created FWF file ko read karke verify karo
df_fwf = pd.read_fwf(fwf_file)
print("\nFWF File se padha gaya Data:")
print(df_fwf)

File 'name.fwf' successfully create ho gayi!

FWF File se padha gaya Data:
    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

CHECKING IN LOAD CSV FILE :-

USE OF .shape :-

In [ ]:
df_read.shape

(3, 3)

USE OF size:-

In [ ]:
df_read.size

9

In [ ]:
df_read.columns

Index(['Name', 'Age', 'City'], dtype='object')

USE OF dtpes :-

In [ ]:
df_read.dtypes

Name    object
Age      int64
City    object
dtype: object

USE OF HEAD :-

In [ ]:
df_read.head()

    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

USE OF TAIL :-

In [ ]:
df_read.tail()

    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

LIVE CODING :-

SEPARATOR :-

In [ ]:
df_csv = pd.read_csv("name.csv", sep=',')
print(df_csv)

    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

In [ ]:
df_tsv = pd.read_csv("name.tsv", sep='\t')
print(df_tsv)

    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura
2  Rahul   19     Agra

USE OF nrows :-

In [ ]:
df = pd.read_csv("name.csv",sep =",",nrows=2)
print(df)

    Name  Age     City
0   Amit   20    Delhi
1  Priya   21  Mathura

USE of usecols :-

In [ ]:
df = pd.read_csv("name.csv",sep =",",usecols=["Age"])
print(df)

   Age
0   20
1   21
2   19

USE OF index_col

In [ ]:
df = pd.read_csv("name.csv",sep =",",index_col="Age")
print(df)

      Name     City
Age
20    Amit    Delhi
21   Priya  Mathura
19   Rahul     Agra

Use of skiprows :-

In [ ]:
df = pd.read_csv("name.csv",sep =",",skiprows=2)
print(df)

   Priya  21 Mathura
0  Rahul  19    Agra

USE OF header :-

In [ ]:
df = pd.read_csv("name.csv",sep =",",header = None)
print(df)

       0    1        2
0   Name  Age     City
1   Amit   20    Delhi
2  Priya   21  Mathura
3  Rahul   19     Agra